### PR TITLE
Recursive fixup

### PR DESCRIPTION
**Pull request by gadomski**
Fixes some comments from @tschaub in #190.

NOTE #190 was for-sure a breaking change, so we should cut a new major release after this PR is merged.

### CODE REVIEW

**Comment by gadomski** [comment]
This probably shouldn't have been merged @jonhealy1 CI wasn't passing.

**Comment by jonhealy1** [comment]
@gadomski I thought it would fix it right now with a pr to bump to v3.0.0. You are right I shouldn't have merged it.

**Comment by jonhealy1** [comment]
I have to change how gh actions pushes to pypi too

**Comment by jonhealy1** [comment]
the tests that fail pass locally .....

**Pull request merged**
